### ISSUE TITLE
the miou of each category of your work on the vkitti dataset?

### ISSUE THREAD

**Issue by longmalongma** [alitabet/morton-net#2]
Thank you very much for your great work, can you tell me the miou of each category of your work on the vkitti dataset? If you can tell me, I will cite your paper and compare it with your work in our experiment. Looking forward to your reply.

**Comment by alitabet** [comment]
Hi @longmalongma, thanks you for your message. Here are the results for vKITTI:


PointNet Late Fusion | Terrain | Tree | Vegetation | Building | Road | Guard Rail | Traffic Sign | Traffic Light | Pole | Misc | Truck | Car | Van | Don't Care | mIoU Area | Overall Acc | Class Acc
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Area 1 | 95.30 | 97.40 | 23.10 | 32.50 | 95.50 | 30.60 | 18.50 | 21.70 | 28.00 | 17.00 | 30.20 | 73.20 | 30.60 | 0.00 | 45.66 | 94.7 | 70.9
Area 2 | 85.50 | 86.60 | 0.00 | 7.30 | 93.60 | 69.90 | 25.30 | 0.00 | 35.80 | 0.00 | 0.00 | 77.80 | 50.50 | 0.30 | 40.95 | 90.5 | 64.7
Area 3 | 43.40 | 88.90 | 82.90 | 61.30 | 72.00 | 0.00 | 2.50 | 0.00 | 8.30 | 5.10 | 5.00 | 78.30 | 15.90 | 1.00 | 35.66 | 81.3 | 52.6
Area 4 | 81.80 | 95.70 | 76.30 | 86.50 | 93.70 | 82.40 | 27.10 | 52.00 | 20.80 | 17.30 | 5.40 | 91.10 | 19.80 | 8.60 | 57.68 | 94.5 | 64.7
Area 5 | 62.40 | 98.50 | 90.10 | 84.80 | 86.80 | 0.00 | 8.50 | 25.30 | 34.90 | 0.00 | 23.50 | 83.50 | 7.10 | 0.70 | 46.57 | 91.8 | 62.5
Area 6 | 93.90 | 98.70 | 0.00 | 0.00 | 94.20 | 76.80 | 57.60 | 0.00 | 16.70 | 13.30 | 0.00 | 92.80 | 51.80 | 0.00 | 45.83 | 97.8 | 65.8
mIoU Class | 77.05 | 94.30 | 45.40 | 45.40 | 89.30 | 43.28 | 23.25 | 16.50 | 24.08 | 8.78 | 10.68 | 82.78 | 29.28 | 1.77 | 45.39 | 91.77 | 63.53

**Comment by longmalongma** [comment]
> Hi @longmalongma, thanks you for your message. Here are the results for vKITTI:
> 
> PointNet Late Fusion	Terrain	Tree	Vegetation	Building	Road	Guard Rail	Traffic Sign	Traffic Light	Pole	Misc	Truck	Car	Van	Don't Care	mIoU Area	Overall Acc	Class Acc
> Area 1	95.30	97.40	23.10	32.50	95.50	30.60	18.50	21.70	28.00	17.00	30.20	73.20	30.60	0.00	45.66	94.7	70.9
> Area 2	85.50	86.60	0.00	7.30	93.60	69.90	25.30	0.00	35.80	0.00	0.00	77.80	50.50	0.30	40.95	90.5	64.7
> Area 3	43.40	88.90	82.90	61.30	72.00	0.00	2.50	0.00	8.30	5.10	5.00	78.30	15.90	1.00	35.66	81.3	52.6
> Area 4	81.80	95.70	76.30	86.50	93.70	82.40	27.10	52.00	20.80	17.30	5.40	91.10	19.80	8.60	57.68	94.5	64.7
> Area 5	62.40	98.50	90.10	84.80	86.80	0.00	8.50	25.30	34.90	0.00	23.50	83.50	7.10	0.70	46.57	91.8	62.5
> Area 6	93.90	98.70	0.00	0.00	94.20	76.80	57.60	0.00	16.70	13.30	0.00	92.80	51.80	0.00	45.83	97.8	65.8
> mIoU Class	77.05	94.30	45.40	45.40	89.30	43.28	23.25	16.50	24.08	8.78	10.68	82.78	29.28	1.77	45.39	91.77	63.53

Thanks!
